### Получить все библиотеки в городе
GET {{baseUrl}}/api/v1/libraries?city={{city}}
Content-Type: application/json

[
  {
    "name": "string",
    "library_uid": "string",
    "address": "string",
    "city": "string"
  }
]

### Получить все книги в библиотеке
GET {{baseUrl}}/api/v1/libraries/{{libraryUid}}/books
Content-Type: application/json

[
  {
    "book_uid": "string",
    "name": "string",
    "author": "string",
    "genre": "string",
    "condition": "string"
  }
]

### Получить информацию по взятым в прокат книгам пользователя
GET {{baseUrl}}/api/v1/reservations
X-User-Name: {{username}}
Content-Type: application/json

[
  {
    "reservation_uid": "string",
    "status": "string",
    "start_date": "string",
    "till_date": "string",
    "book": {
      "book_uid": "string",
      "name": "string",
      "author": "string",
      "genre": "string"
    },
    "library": {
      "library_uid": "string",
      "name": "string",
      "address": "string",
      "city": "string"
    }
  }
]

### Взять книгу
POST {{baseUrl}}/api/v1/reservation
X-User-Name: {{username}}
Content-Type: application/json
# REQUEST
{
  "book_uid": "string",
  "library_uid": "string",
  "till_date": "string"
}

# RESPONSE
{
  "reservation_uid": "string",
  "status": "string",
  "start_date": "string",
  "till_date": "string",
  "book": {
    "book_uid": "string",
    "name": "string",
    "author": "string",
    "genre": "string"
  },
  "library": {
    "library_uid": "string",
    "name": "string",
    "address": "string",
    "city": "string"
  },
  "rating": "number"
}

### Верунть книгу
POST {{baseUrl}}/api/v1/reservation/{{reservation_uid}}/return
X-User-Name: {{username}}
Content-Type: application/json

{
  "condition": "string"
}

### Получить рейтинг пользователя
GET {{baseUrl}}/api/v1/rating
X-User-Name: {{username}}
Content-Type: application/json

{
  "stars": "number"
}