// Code generated by mockery v2.33.3. DO NOT EDIT.

package ratings

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetUserRating provides a mock function with given fields: ctx, username
func (_m *MockClient) GetUserRating(ctx context.Context, username string) (Rating, error) {
	ret := _m.Called(ctx, username)

	var r0 Rating
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (Rating, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) Rating); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(Rating)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetUserRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRating'
type MockClient_GetUserRating_Call struct {
	*mock.Call
}

// GetUserRating is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockClient_Expecter) GetUserRating(ctx interface{}, username interface{}) *MockClient_GetUserRating_Call {
	return &MockClient_GetUserRating_Call{Call: _e.mock.On("GetUserRating", ctx, username)}
}

func (_c *MockClient_GetUserRating_Call) Run(run func(ctx context.Context, username string)) *MockClient_GetUserRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetUserRating_Call) Return(_a0 Rating, _a1 error) *MockClient_GetUserRating_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetUserRating_Call) RunAndReturn(run func(context.Context, string) (Rating, error)) *MockClient_GetUserRating_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
